# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gomanize < Formula
  desc "Romanize Devanagari (Hindi) into readable Latin script"
  homepage "https://github.com/budhash/gomanize"
  version "1.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/budhash/gomanize/releases/download/v1.2.1/gomanize_1.2.1_darwin_amd64.tar.gz"
      sha256 "b2103610424c9578dbe87be3437f6928e9dee503f77bebb8c705c16e9bc8b258"

      define_method(:install) do
        bin.install "gomanize"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/budhash/gomanize/releases/download/v1.2.1/gomanize_1.2.1_darwin_arm64.tar.gz"
      sha256 "5df722cda4da1516b88ecbb867881cd8ccea6eaacd97c0ec95704a40672ece03"

      define_method(:install) do
        bin.install "gomanize"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/budhash/gomanize/releases/download/v1.2.1/gomanize_1.2.1_linux_amd64.tar.gz"
      sha256 "88c35b01ee8d2fc950fb7ef71cbdaef57e88814b9698630cc9e3f9e5e873f646"
      define_method(:install) do
        bin.install "gomanize"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/budhash/gomanize/releases/download/v1.2.1/gomanize_1.2.1_linux_arm64.tar.gz"
      sha256 "aa75380113fa67a99f68b6179529d76195ba5de0c71e9ae9c067c0b6afd2c5f3"
      define_method(:install) do
        bin.install "gomanize"
      end
    end
  end

  test do
    assert_match "namaste", shell_output("#{bin}/gomanize नमस्ते")
  end
end
